-- database/seeds/students_seed.sql
INSERT INTO students (admission_number, name, grade, school) VALUES
('S001', 'JEPTANUI, CONIE', '9', 'REHEMA JUNIOR SCHOOL'),
('S002', 'JEPKOECH, IVY', '9', 'REHEMA JUNIOR SCHOOL'),
('S003', 'SALLY, ELIZABETH', '9', 'REHEMA JUNIOR SCHOOL'),
('S004', 'MONICA WAIRIMU', '9', 'REHEMA JUNIOR SCHOOL'),
('S005', 'EKIDOR, ALFRED', '9', 'REHEMA JUNIOR SCHOOL'),
('S006', 'NELIMA, BELINDA', '9', 'REHEMA JUNIOR SCHOOL'),
('S007', 'PENINAH WANGARI', '9', 'REHEMA JUNIOR SCHOOL');